databases:
  - name: rainbowkids_db
    databaseName: rainbowkids
    user: rainbowkids

services:
  - type: web
    name: rainbowkids
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd rainbowkids && gunicorn rainbowkids.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: rainbowkids_db
          property: connectionString
